version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017
      - SECRET_KEY=your_secret_key
    depends_on:
      - mongo
    networks:
      - app-network

    db:
    image: postgres:15
    container_name: yourapp-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db_data: