version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

networks:
  app-network:
